foreground            #dee4e1
background            #0e1513
cursor                #dee4e1

active_border_color   #84d5c4
inactive_border_color #3f4946

active_tab_foreground   #00382f
active_tab_background   #84d5c4
inactive_tab_foreground #bec9c5
inactive_tab_background #3f4946

# ألوان الترمينال الأساسية
color0 #0e1513
color8 #3f4946

color1 #ffb4ab
color9 #ffb4ab

color2 #84d5c4
color10 #84d5c4

color3 #abcae4
color11 #abcae4

color4 #b1ccc4
color12 #b1ccc4

color5 #a0f2df
color13 #a0f2df

color6 #cde8e0
color14 #cde8e0

color7 #dee4e1
color15 #bec9c5
